### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-vc133#2]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by Marymota** [comment]
![INC-5312: Missing image](https://user-images.githubusercontent.com/20130249/183514985-e5f2cc7c-c322-4b89-8f3f-698bb75292d4.png)

Added onError event to replace empty img src with placeholder image at:
frontend/src/index.js 
frontend/src/components/ItemPreview.js
